pub mod best_fit;
pub mod best_fit_threshold;
pub mod cosine_similarity;
pub mod dot_product;
pub mod first_fit;
pub mod norm_based_greedy;
pub mod perp_distance;
pub mod weighted_dot_product;
pub mod worst_fit;
