[package]
name = "storage-disk-advanced-example"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
dslab-core = { path = "../../crates/dslab-core" }
dslab-storage = { path = "../../crates/dslab-storage" }
dslab-models = { path = "../../crates/dslab-models" }
sugars = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.14"
env_logger = "0.9.0"
