[package]
name = "storage-disk-advanced-example"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
simcore = "0.1"
dslab-models = { path = "../../crates/dslab-models" }
dslab-storage = { path = "../../crates/dslab-storage" }
env_logger = "0.10.0"
log = "0.4.14"
rand = "0.8.4"
sugars = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
