[package]
name = "dslab-mp-python"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
dslab-mp = { path = "../dslab-mp" }
serde = { version = "1.0", features = ["derive"] }

[dependencies.pyo3]
version = "0.16.5"
features = ["auto-initialize"]
