[package]
name = "cloud_plugin_example"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../../crates/core" }
cloud-plugin = { path = "../../crates/cloud-plugin" }
rand = "0.8.3"
sugars = "3.0.0"
log = "0.4"
env_logger = "0.8.4"