[package]
name = "network-simple-example"
version = "0.1.0"
edition = "2021"

[dependencies]
simcore = { path = "../../crates/simcore" }
network = { path = "../../crates/network" }
env_logger = "0.8.4"
sugars = "3.0.0"
