[package]
name = "serverless_in_the_wild"
version = "0.0.1"
edition = "2021"

[dependencies]
simcore = { path = "../../crates/simcore" }
csv = "1.1"
rand = "0.8.4"
rand_pcg = "0.3.1"
serverless = { path = "../../crates/serverless" }
serverless-extra = { path = "../../crates/serverless-extra" }
