[package]
name = "disk-example"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../../crates/core" }
storage = { path = "../../crates/storage" }
sugars = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
