resources:
  - name: c5large_vm1
    speed: 200
    cores: 1
    memory: 4096
    price: 0.085
  - name: c5large_vm2
    speed: 200
    cores: 1
    memory: 4096
    price: 0.085
  - name: c5large_vm3
    speed: 200
    cores: 1
    memory: 4096
    price: 0.085
  - name: c5xlarge_vm1
    speed: 400
    cores: 1
    memory: 8192
    price: 0.17
  - name: c5xlarge_vm2
    speed: 400
    cores: 1
    memory: 8192
    price: 0.17
  - name: c5xlarge_vm3
    speed: 400
    cores: 1
    memory: 8192
    price: 0.17
  - name: c52xlarge_vm1
    speed: 800
    cores: 1
    memory: 16384
    price: 0.34
  - name: c52xlarge_vm2
    speed: 800
    cores: 1
    memory: 16384
    price: 0.34
  - name: c52xlarge_vm3
    speed: 800
    cores: 1
    memory: 16384
    price: 0.34
network:
  model: ConstantBandwidth
  bandwidth: 30
  latency: 1000
