[package]
name = "compute_multicore"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../../crates/core" }
compute = { path = "../../crates/compute" }
log = "0.4.14"
env_logger = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
sugars = "3.0.0"
