[package]
name = "faas-example"
version = "0.0.1"
edition = "2021"

[dependencies]
dslab-core = { path = "../../crates/dslab-core" }
dslab-faas = { path = "../../crates/dslab-faas" }
log = "0.4.14"
env_logger = "0.9.0"
