[package]
name = "faas-parallel-example"
version = "0.0.1"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.14", features = ["derive"] }
dslab-core = { path = "../../crates/dslab-core" }
dslab-faas = { path = "../../crates/dslab-faas" }
