[package]
name = "master-workers"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../../core" }
compute = { path = "../../compute" }
rand = "0.8.4"
rand_pcg = "0.3.1"
sugars = "3.0.0"
