//! Hard drive linear power model.

use crate::power::hard_drive::HardDrivePowerModel;

/// Hard drive linear power model.
///
/// Hard drive power consumption mainly consists of static consumption 90%, the rest 10% are
/// generated by I/O activities.
/// (c) https://www.newertech.com/Static/articles/article_greenercomp_hhdpower.php
///
/// Default hard drive is Toshiba X300 Pro with 10W of maximim consumption.
#[derive(Clone)]
pub struct LinearPowerModel {
    static_percentage: f64,
    total_consumption: f64,
}

impl LinearPowerModel {
    /// Creates linear power model.
    pub fn new() -> Self {
        Self {
            static_percentage: 0.9,
            total_consumption: 10.,
        }
    }

    /// Creates linear power model with custom HDD model.
    pub fn custom_model(total_consumption: f64) -> Self {
        Self {
            static_percentage: 0.9,
            total_consumption,
        }
    }
}

impl Default for LinearPowerModel {
    fn default() -> Self {
        Self::new()
    }
}

impl HardDrivePowerModel for LinearPowerModel {
    fn get_power(&self, utilization: f64) -> f64 {
        (self.static_percentage + (1. - self.static_percentage) * utilization) * self.total_consumption
    }
}
