[package]
name = "throughput-model-comparison"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
simcore = "0.1"
dslab-models = { path = "../../crates/dslab-models" }
sugars = "3.0.0"
num = "0.4.0"
rand = "0.8.5"
rand_pcg = "0.3.1"
