[package]
name = "callbacks-vs-async"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
dslab-core = { path = "../../crates/dslab-core", features = ["async_mode"] }
serde = { version = "1.0", features = ["derive"] }
