[package]
name = "serverless-in-the-wild"
version = "0.0.1"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
dslab-core = { path = "../../crates/dslab-core" }
dslab-faas = { path = "../../crates/dslab-faas" }
dslab-faas-extra = { path = "../../crates/dslab-faas-extra" }
csv = "1.1"
rand = "0.8.4"
rand_pcg = "0.3.1"
serde_yaml = "0.8"
