base_config:
  hosts:
    - cores: 12
      resources:
        - name: mem
          quantity: 26624
      invoker: FIFOInvoker
      count: 8
  coldstart_policy: FixedTimeColdStartPolicy[keepalive=1200,prewarm=0]
  cpu_policy: contended
  idle_deployer: BasicDeployer
schedulers:
  - LocalityBasedScheduler[warm_only=false]
  - RandomScheduler[seed=1]
  - LeastLoadedScheduler[prefer_warm=false,use_invocation_count=true,avoid_queueing=true]
  - RoundRobinScheduler
  - HermodScheduler[prefer_warm=false,use_invocation_count=true,avoid_queueing=true]
