[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
decorum = "0.3.1"
downcast-rs = "1.2.0"
log = "0.4"
rand = "0.8.4"
rand_pcg = "0.3.1"
serde = "1.0"
erased-serde = "0.3"
serde_json = "1.0"
serde_type_name = "0.2.0"
