[package]
name = "ping-pong"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../../crates/core" }
clap = { version = "3.0.14", features = ["cargo"] }
log = "0.4.14"
env_logger = "0.9.0"
sugars = "3.0.0"
