[package]
name = "faas-synthetic-trace-example"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
dslab-core = { path = "../../crates/dslab-core" }
dslab-faas = { path = "../../crates/dslab-faas" }
rand_distr = "0.4.3"
rand_pcg = "0.3.1"
