[package]
name = "dag-run-experiment"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
dslab-dag = { path = "../../crates/dslab-dag" }
clap = { version = "4.1.9", features = ["derive"] }
serde_json = "1.0"
