[package]
name = "master-workers2"
version = "0.1.0"
edition = "2021"

[dependencies]
core2 = { path = "../../crates/core2" }
log = "0.4.14"
env_logger = "0.9.0"
rand = "0.8.4"
rand_pcg = "0.3.1"
sugars = "3.0.0"
