[package]
name = "shared-disk-example"
version = "0.1.0"
edition = "2021"

[dependencies]
simcore = { path = "../../crates/simcore" }
storage = { path = "../../crates/storage" }
sugars = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.14"
env_logger = "0.9.0"
